#pragma once

enum {
	NETBUS_MSG_INVAL = 0, 
	NETBUS_MSG_RESOLVE, 
	NETBUS_MSG_ADD, 
	NETBUS_MSG_CALL, 
	NETBUS_MSG_LIST,
	NETBUS_MSG_ACK, 
	NETBUS_MSG_MAX
}; 

enum {
	NETBUS_ATTR_STATUS, 
	NETBUS_ATTR_OBJID, 
	NETBUS_ATTR_OBJPATH, 
	NETBUS_ATTR_METHOD, 
	NETBUS_ATTR_ACTIVE, 
	NETBUS_ATTR_NOREPLY,
	NETBUS_ATTR_MAX
}; 
